# ===================================================================
# Spring Boot configuración para el perfil "pre".
#
# Esta configuración sobreescribe al fichero application.yml.
# ===================================================================

debug:
  false

spring:
  devtools:
    restart:
      enabled: true   
      
server:
  ssl:
    key-store: /apli/colaboradores/certificados/p12/oauth-server-colaboradores.p12
    key-store-password: confianza2020
    key-store-type: PKCS12
    key-alias: oauth-server-colaboradores     

oauthData:
  database:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/oauth_colaboradores
    user: oauthuser
    password: movaseoauth
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxIdle: 50
    timeBetweenEvictionRunsMillis: 30000
    removeAbandoned: true
    removeAbandonedTimeout: 60
    logAbandoned: true
    testWhileIdle: true

# ===================================================================
# Movcli specific properties
# ===================================================================

movcli:
  logger:
    logstash:
      - name: clientlog
        appender:
          destination: localhost:4560 
        encoder:
          includeMDC: true
      - name: auditlog
        appender:
          destination: localhost:4561
        encoder:
          includeMDC: true

ldap:
  url: ldap://172.20.5.20:389
  domain: qa.pvt
  rootDn: DC=qa,DC=pvt
  userSearch: (&(sAMAccountName={0})(ObjectClass=organizationalPerson)(ObjectClass=person))
  searchBase: DC=fe,DC=local
  groupSearchBase: DC=qa,DC=pvt 
  searchFilter: (&(member={0}) (objectclass=group))
  managerDn: movilidad@fe.local
  managerPwd: 5KMuewi