# ===================================================================
# Spring Boot configuración.
#
# Esta configuración será sobreescrita por el perfil de Spring en uso,
# por ejemplo application-dev.yml si tu usas el perfil "dev".
# ===================================================================

spring:
  application:
    name: oauth-server-asesores
    
  devtools:
    restart:
      enabled: false
  
server:
  port: 9999
  context-path: /uaa

logging:
  level:
    org.springframework.security: DEBUG
      
# ===================================================================
# Movcli specific properties
# ===================================================================

movcli:      
  cors: 
      enabled: true 
      mapping: "/**" 
      allowedOrigins: "*" 
      allowedMethods: POST,GET,OPTIONS,DELETE 
      maxAge: 3600
  jaxb:
    marshaller:
      packagescan: org.fmbbva.movcli.piloto.ws.model
      
oauth2:
  client:
    id: portal
    resource-id: portal
    client-id: demo
    client-secret: secret_demo
    authorized-grant-types: password, refresh_token 
    access-token-validity-seconds: 600
    refresh-token-validity-seconds: 600
    scopes: read, write, trust       


ldap:
  url: ldap://172.21.1.13:389
  domain: cnpdes.local
  rootDn: dc=cnpdes,dc=local
  userSearch: (&(sAMAccountName={0})(ObjectClass=organizationalPerson)(ObjectClass=person))
  searchBase: ou=Desarrollo
  groupSearchBase: OU=Grupos,OU=Gestion 
  searchFilter: (&(member={0}) (objectclass=group))
  managerDn: srv_mov_ldap@cnpdes.local
  managerPwd: Mov.4325
        
